LICENSE

Use Apache 2.0 license.

---

docs/developer/decision-records/2022-06-20-mvd-onboarding/README.md

Decision record log document describing the infrastructure needed to enable the Verifiable Credentials verification in MVD onboarding scenario. 
linked to https://github.com/agera-edc/MinimumViableDataspace/issues/18

MVD onboarding infrastructure - ADR 

---

.github/actions/gradle-setup/action.yml
deployment/data/MVD.postman_collection.json
extensions/mock-credentials-verifier/src/main/java/org/eclipse/dataspaceconnector/mvd/MockCredentialsVerifier.java
extensions/mock-credentials-verifier/src/test/java/org/eclipse/dataspaceconnector/mvd/MockCredentialsVerifierTest.java
system-tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/utils/TransferSimulationUtils.java

This PR contains:
- Upgrade of the EDC revision
- Fixes of breaking changes
Linked to: https://github.com/agera-edc/MinimumViableDataspace/issues/162

Upgrade EDC revision  (#163)

---

.github/actions/gradle-setup/action.yml
.github/workflows/deploy.yaml
extensions/mock-credentials-verifier/src/main/java/org/eclipse/dataspaceconnector/mvd/MockCredentialsVerifier.java
extensions/mock-credentials-verifier/src/test/java/org/eclipse/dataspaceconnector/mvd/MockCredentialsVerifierTest.java
extensions/policies/src/main/java/org/eclipse/dataspaceconnector/mvd/SeedPoliciesExtension.java

Update EDC version to milestone 5
Agreed upon MVD EDC target version
Scope updated to reflect doc at https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/b71a14c44f3718ce4a2c9b40769bc70d863716ad/docs/developer/policy-engine.md.
Updated DataDashboard because of DTO change.
https://github.com/agera-edc/MinimumViableDataspace/issues/224

EDC version update to milestone 5

---

.github/workflows/deploy.yaml
.github/workflows/destroy.yaml
README.md

Check that the user-provided prefix when running the Deploy action adheres to Azure naming conventions (and restrictions).
Run with valid prefix: https://github.com/agera-edc/MinimumViableDataspace/actions/runs/2825298663
Sample failed run with invalid prefix: https://github.com/agera-edc/MinimumViableDataspace/actions/runs/2825083999
https://github.com/agera-edc/MinimumViableDataspace/issues/152

CD: check name prefix format in manual deployment

---

.github/workflows/cd.yaml
.github/workflows/cloud-cd.yaml
.github/workflows/deploy.yaml
build.gradle.kts

- Publish Gatling reports (HTML) as downloadable pipeline artifact. (See sample at https://github.com/agera-edc/MinimumViableDataspace/actions/runs/2831636345)
- Upload test coverage data to CodeCov: https://app.codecov.io/gh/agera-edc/MinimumViableDataspace/pulls
These are implemented exactly like in EDC.
Improved reporting, aligned with EDC practices.
https://github.com/agera-edc/MinimumViableDataspace/issues/172

CI: Test reports

---

.github/workflows/cd.yaml
.github/workflows/check.yaml
.github/workflows/cloud-cd.yaml

Run CI (verification and test deployment) on merge to `main` branch.
Provide a baseline to verify that the CI on main branch is green.
With this setup, downstream projects run their pipelines when they refresh main, so they can ensure they have a working base setup.
none

chore: Run CI on main branch

---

docs/developer/decision-records/2022-06-15-registration-service/README.md

Update registration service ADR with details of the dataspace registration policy used in MVD.
Behavior described is already implemented in previous PRs (in Registration Service)
https://github.com/agera-edc/MinimumViableDataspace/issues/11

ADR update for registration policy

---

.github/actions/gradle-setup/action.yml
.github/workflows/deploy.yaml
README.md
system-tests/README.md
system-tests/resources/cli-tools/Dockerfile
system-tests/resources/cli-tools/entrypoint.sh
system-tests/resources/cli-tools/validate_onboarding.sh

- As the registration service now has an endpoint to fetch the record of a participant, this can be utilized during participant onboarding to verify that onboarding completed successfully or not.
- Update to system-tests/README.md necessary for a successful build of Registration service
- Update to README.md and system-tests/README.md for changed behavior of container `cli-tools`indicating successful execution of scripts.
- Add health check to `system-tests/resources/cli-tools/Dockerfile` to have an indicator when container `cli-tools` is finished.
- Updated to use latest version of registration service.
Validate if a participant onboarded successfully or not.
Closes https://github.com/agera-edc/MinimumViableDataspace/issues/46

Verify participant onboarding status

---

Vision Demonstrator/Vision Demonstrator Introduction.md

Added Figma File local copy
_Briefly describe WHAT your pr changes, which features it adds/modifies._

Add ReadMe file for the Vision Demonstrator

---

system-tests/src/test/java/org/eclipse/edc/system/tests/identityhub/IdentityHubIntegrationTest.java

Fixes a compile error introduced by the upgrade to Nimbus 9

fix: compile error due to Nimubs upgrade

---

extensions/policies/build.gradle.kts
extensions/policies/src/main/java/org/eclipse/edc/mvd/RegionConstraintFunction.java
extensions/policies/src/test/java/org/eclipse/edc/mvd/RegionConstraintFunctionTest.java
extensions/refresh-catalog/src/main/java/org/eclipse/edc/mvd/RegistrationServiceNodeDirectory.java
launchers/connector/build.gradle.kts
launchers/registrationservice/build.gradle.kts
settings.gradle.kts
system-tests/build.gradle.kts
system-tests/src/test/java/org/eclipse/edc/system/tests/identityhub/IdentityHubIntegrationTest.java

Update Identity Hub dependencies.
Dependencies were broken.

fix: Update Identity Hub dependencies

---

deployment/azure/seed_vcs.sh
extensions/policies/build.gradle.kts
extensions/policies/src/main/java/org/eclipse/edc/mvd/RegionConstraintFunction.java
extensions/policies/src/main/java/org/eclipse/edc/mvd/SeedPoliciesExtension.java
extensions/policies/src/test/java/org/eclipse/edc/mvd/RegionConstraintFunctionTest.java
launchers/connector/build.gradle.kts
launchers/registrationservice/build.gradle.kts
settings.gradle.kts
system-tests/resources/cli-tools/entrypoint.sh
system-tests/resources/vault/company1/company1-vault.properties
system-tests/resources/vault/company2/company2-vault.properties
system-tests/src/test/java/org/eclipse/edc/system/tests/identityhub/IdentityHubIntegrationTest.java

Update `RegionConstraintFunction` to comply with recent IdentityHub updates concerning the format of the returned Verifiable Credentials.
Refactor.
We also take opportunity of this PR to remove the no longer used Gaia-X Verifiable Credentials pushed in participants Identity Hub.
Closes #120 #121.

refactor: Update `RegionConstraintFunction`

---

README.md
system-tests/README.md

Fix readme files.
Documentation.
Remove Powershell related documentation.
Closes #125 #126

docs: Fix readme files

---

deployment/azure/docker/company1.env
deployment/azure/docker/company2.env
deployment/azure/docker/company3.env

Fix `.env` files.
Repair `Cloud-CD` workflow.

fix: Fix cloud Docker Compose `.env` files

---

README.md
docs/developer/continuous-deployment/continuous_deployment.md
system-tests/README.md

docs: fix typos in readme

---

deployment/modules/connector/controlplane.tf
gradle/libs.versions.toml

Secure federated catalog query API
Closes #291

feat: secure federated catalog query api

---

.github/dependabot.yml
README.md
extensions/dcp-impl/src/main/java/org/eclipse/edc/demo/dcp/core/DcpPatchExtension.java
extensions/dcp-impl/src/main/java/org/eclipse/edc/demo/dcp/core/DefaultScopeMappingFunction.java

improves the README outlining the custom extensions, hacks and workarounds that were put in place for MVD.
documentation

docs(readme): improve README

---

deployment/assets/env/consumer_connector.env
deployment/assets/env/provider_catalogserver.env
deployment/assets/env/provider_connector_manufacturing.env
deployment/assets/env/provider_connector_qna.env
extensions/dcp-impl/src/main/java/org/eclipse/edc/demo/dcp/core/DcpPatchExtension.java
gradle/libs.versions.toml
launchers/catalog-server/build.gradle.kts

Incorporates  [#4470](https://github.com/eclipse-edc/Connector/pull/4470) by applying the setting for a clean JSON-LD context in output objects.

chore: clean JSON-LD context output

---

deployment/modules/identity-hub/identityhub.tf
extensions/superuser-seed/src/main/java/org/eclipse/edc/identityhub/seed/ParticipantContextSeedExtension.java
extensions/superuser-seed/src/test/java/org/eclipse/edc/identityhub/seed/ParticipantContextSeedExtensionTest.java
gradle/libs.versions.toml

fixes a compile error after latest IH changes
Closes #336

fix: compile error

---

deployment/assets/env/issuerservice.env
deployment/postman/MVD K8S.postman_environment.json
deployment/postman/MVD Local Development.postman_environment.json
deployment/postman/MVD.postman_collection.json

Integrates issuance process admin API for monitoring issuance processes on the issuer side.

chore: integrates issuance process admin API

---

seed-k8s.sh
seed.sh

changes dcp issuance base path after IH change https://github.com/eclipse-edc/IdentityHub/pull/636

feat: changes dcp issuance base path

---

deployment/postman/MVD Local Development.postman_environment.json
deployment/postman/MVD.postman_collection.json
launchers/issuerservice/src/main/java/org/eclipse/edc/issuerservice/seed/attestation/DemoAttestationSourceFactory.java

fix after upstream changes to issuer admin APIs

chore: fix after upstream changes to issuer admin APIs

---

gradle/libs.versions.toml
launchers/identity-hub/build.gradle.kts

Fixed typos in IdentityHub BOMs in libs-versions.toml
Updated usages to fixed typo BOMs.
Closes #450

fix: typo in IdentityHub BOMs

---

deployment/postman/MVD.postman_collection.json

fix after credential definition change
Ref: https://github.com/eclipse-edc/IdentityHub/pull/678

chore: fix after credential definition change

---

README.md

adds a bit of docu about MVD versions

docs: add section about versions

---

build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts

switch to edc build plugin 1.0.0 published on gradle plugin portal

chore: switch to edc build plugin 1.0.0
