docs/developer/continuous_deployment.md
[CD documentation](https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace/blob/main/docs/developer/continuous_deployment.md) contains outdated information about deploying the `DataDashboard`.
The `DataDahboard` is now being built and deployed as part of the `Deploy` pipeline.
Thi PR removes last section in the DC documentation about the `DataDahboard` and fixes a link formatting issue.
Related to downstream issue https://github.com/agera-edc/MinimumViableDataspace/issues/195.
=> Remove outdated DataDashboard section (#197)

.github/workflows/cd.yaml
Linked to [#56 ](https://github.com/agera-edc/MinimumViableDataspace/issues/56)
This PR introduces a step that checks if the repository has Azure secrets set up. If yes -> proceeds with the CD workflow, if not -> the checks are disabled.
The reason to introduce such step is to not fail the workflow in the PRs from forks to the upstream MVD repository.
Please note that it's a temporary solution. 
A solution that allows to run all tests (eg. on local resources) in PR from forks will be introduced at later stage.
=> CI:  Skip Azure resources deployment if Azure secrets are not set up

.github/actions/generate-key/action.yml, .github/workflows/cd.yaml, .github/workflows/deploy.yaml, deployment/terraform/dataspace/main.tf, deployment/terraform/dataspace/outputs.tf, deployment/terraform/dataspace/variables.tf, docs/developer/decision-records/2022-06-15-registration-service/README.md
Deployment of GAIA-X Authority DID document. The simulated GAIA-X DID is going to be part of the CD pipeline and deployed/destroyed together with other resources.
MVD GAIA-X authority should have DID document related to it.
- This PR contains also some renaming to make usage of the names `registry`, `registration service` consistent.
- Removing `branches: [ main ]` from the workflow triggers to enable checks on all PRs not only PRs against main branch
Closes https://github.com/agera-edc/MinimumViableDataspace/issues/151 and https://github.com/agera-edc/MinimumViableDataspace/issues/180
=> GAIA-X DID document deployment

docs/developer/decision-records/2022-06-15-registration-service/README.md
Removes references to X.509 certificates from the Registration Service ADR.
The type of certificates is defined by the subsequent [ADR for participant onboarding](https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace/tree/main/docs/developer/decision-records/2022-06-20-mvd-onboarding#public-key-infrastructure).
Closes [downstream issue #199](https://github.com/agera-edc/MinimumViableDataspace/issues/199)
=> Registration Service ADR: Remove X.509 references

.github/workflows/deploy.yaml, deployment/terraform/dataspace/main.tf, deployment/terraform/dataspace/outputs.tf, deployment/terraform/dataspace/variables.tf, deployment/terraform/participant/main.tf, deployment/terraform/participant/outputs.tf, deployment/terraform/participant/variables.tf, docs/developer/decision-records/2022-07-19-cd-vault-secrets/README.md, system-tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/BlobTransferIntegrationTest.java
- Avoid attempting to use Managed Identity for Azure login for test runs
- Deploy AKV secrets in CD, rather than Terraform.
Resolve two causes of failing CD runs.
- Ensure correct identity is picked up when running tests. [As reported](https://github.com/orgs/github-community/discussions/20830), a Managed Identity is sometimes unexpectedly attached to GitHub runners.
- Account for role assignment propagation time. See ADR included for details.
Closes https://github.com/agera-edc/MinimumViableDataspace/issues/205
=> Bug/205 fix CD identity / Key Vault RBAC propagation issues

.github/workflows/deploy.yaml, deployment/curl-upgrade.sh, deployment/terraform/dataspace/main.tf, deployment/terraform/participant/main.tf
Cloud deployments are failing during health check steps. So far what we have observed that it is due to Azure Container Instance taking longer to start up or getting restarted initially which make the `curl` health check call to fail.
`curl` is supposed to be retyring in such scenario but it doesn't retry in case of a connection is reset by peer (more in the linked issue). To overcome these two things are added in this PR:
- Update Azure Container Instance liveness check probe to give container more time before it is ready for a health check.
- curl request is done now with `--retry-all-errors` flag which retries on more error codes, so it covers the above-mentioned situation when connection is reset by peer. But in order to have this flag available for curl we need to have curl version …
=> Cloud Deployment: Fix MVD cloud deployment health check failure

.github/actions/gradle-setup/action.yml, .github/workflows/cd.yaml, .github/workflows/check.yaml, .github/workflows/deploy.yaml, deployment/terraform/dataspace/main.tf, deployment/terraform/dataspace/outputs.tf, extensions/refresh-catalog/src/main/java/org/eclipse/dataspaceconnector/mvd/RegistrationServiceNodeDirectoryExtension.java, gradle.properties, system-tests/README.md, system-tests/docker-compose.yml, system-tests/resources/cli-tools/Dockerfile, system-tests/resources/cli-tools/entrypoint.sh, system-tests/resources/register-participants.sh, system-tests/resources/webdid/consumer-eu/did.json, system-tests/resources/webdid/consumer-us/did.json, system-tests/resources/webdid/provider/did.json
Access to the Registration Service API is authenticated with JWS. Adapted accordingly:
- the Registration Service CLI call in the deployment pipeline
- the federated Directory implementation in EDC, for retrieving the participants list
Authentication ensures that only actors who can assert their control of a did:web identifier can register that identifier as a dataspace participant. 
- Updated Registration service commit dependency for the required JWS support
- Updated Registration service URLs given new port and URL mapping (https://github.com/agera-edc/RegistrationService/pull/14)
- Updated EDC version because of a required fix (`#1575`)
- The curl command to check registration service is up doesn't work anymore, since a JWS is required. I've remove the `curl` command and let the …
=> Registration Service JWS authentication

.github/workflows/deploy.yaml, deployment/data/MVD.postman_collection.json, deployment/seed-data.sh, system-tests/docker-compose.yml, system-tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/utils/TransferSimulationUtils.java
Adds a suffix to asset IDs and names to make them unique across the dataspace.
To avoid overwriting of assets in the catalog.
_this is as of yet untested, because neither can I log into my Azure Subscription (due to a weird login loop), nor can I run it locally due to compile errors._
Closes #7
=> feat add participant-id as suffix to assets

.github/workflows/deploy.yaml, deployment/terraform/dataspace/main.tf
Include Registration service enrollment api endpoint in Dataspace Authority DID document.
The Enrollment API url should be resolved from the Dataspace DID. A subsequent PR will implement that.
Example DID: https://mvd144dataspacedid.z16.web.core.windows.net/.well-known/did.json
```
{
"@context": [
"https://www.w3.org/ns/did/v1",
{
"@base": "did:web:mvd144dataspacedid.z16.web.core.windows.net"
}
],
"authentication": [
"#identity-key-authority"
],
"id": "did:web:mvd144dataspacedid.z16.web.core.windows.net",
"service": [
{
"id": "#registration-url",
"serviceEndpoint": "http://mvd144-registration-mvd.northeurope.azurecontainer.io:8182/authority",
"type": "RegistrationUrl"
}
],
"verificationMethod": [
{
"controller": "",
"id": "#identity-key-authority",
"publicKeyJwk": {
"crv": "P-256",
"kid": …
```
=> Add EnrollmentUrl to Did document

CHANGELOG.md, launcher/Dockerfile, launcher/build.gradle.kts, launcher/src/main/resources/logging.properties
Use JDKLogger in MVD in order to get logs pushed into Application Insights.
Connector logs:
* Cloud: see traces in Application Insights for "jdklogger2" deployment: https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/9d236f09-93d9-4f41-88a6-20201a6a1abc/resourceGroups/rg-jdklogger2/providers/Microsoft.Insights/components/jdklogger2-appinsights/searchV1
* Local: see "docker-compose logs" section in https://github.com/agera-edc/MinimumViableDataspace/runs/7666891440?check_suite_focus=true
Application logs were not visible in Application Insights.
At the moment Application Insights is configured with default settings, which means that only logs with level INFO and above are captured. This can be configured as described here: …
=> JDK Logger Monitor

.github/actions/gradle-setup/action.yml, .github/workflows/deploy.yaml, deployment/terraform/participant/outputs.tf, system-tests/resources/cli-tools/entrypoint.sh, system-tests/resources/webdid/registration-service/did.json
Let Registration Service CLI use Enrollment URL from DID Document, instead of passing it from CD pipeline.
The participant should only have to know the DID of the dataspace they intend to join. The enrollment URL can be resolved automatically.
https://github.com/agera-edc/MinimumViableDataspace/issues/43
=> Registration Service CLI: use Enrollment URL from DID Document

.github/actions/gradle-setup/action.yml
Updates CI and local build files to use EDC Version `0.0.1-milestone-5.1` which includes a critical fix regarding the catalog. 
The catalog clearing process was fixed after M5 was released, so that fix never found its way into MVD.
Checking out and building locally the EDC Code base was replaced by depending against artifacts from MavenCentral.
RegistrationService and IdentityHub are still being checked out and built locally.
Closes https://github.com/agera-edc/minimumViableDataspace/issues/193
=> chore: bump EDC version to M5.1

docs/developer/continuous-deployment/continuous_deployment.md, resources/setup_azure_ad/.gitignore, resources/setup_azure_ad/gh-actions.tf, resources/setup_azure_ad/main.tf, resources/setup_azure_ad/mvd-runtimes.tf, resources/setup_azure_ad/outputs.tf, resources/setup_azure_ad/set-gh-secrets.sh, resources/setup_azure_ad/variables.tf
Adds terraform scripts to setup AppRegs and SPs for MVD in Azure AD automatically. Updates documentation.
Tested on EDC upstream.
to provide an alternative to the manual way through Azure Portal.
.
=> docs: added option to setup AAD using terraform

build.gradle.kts
Removed unnecessary apply of jacoco plugin.
jacoco plugin is applied twice in the build.gradle.kts.
No issue, just a cleanup.
=> Cleanup: Removed unecessary jacoco apply plugin.

.github/workflows/check.yaml, .github/workflows/codeql-analysis.yml, build.gradle.kts, docs/developer/decision-records/2022-08-15-code-quality-tooling/README.md
- Run checkstyle on PRs in both upstream and forks.
- Run CodeQL on  PRs in both upstream and forks.
workflow failure due to checkstyle as an example: https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace/runs/7837971765?check_suite_focus=true
Both Checkstyle and CodeQL are already in use in the EDC framework, so these tools are the natural choice in related projects like the Identity Hub as well.
Relates to https://github.com/agera-edc/MinimumViableDataspace/issues/252
=> Add codeql and checkstyle

system-tests/README.md
Small doc change to indicate the correct version of the `edc` to use when building the mvd
Documentation was out of sync with the current process
Closes https://github.com/agera-edc/MinimumViableDataspace/issues/273
=> feat: Updated Documentation For Release Milestone 5.1

deployment/terraform/dataspace/dataspace-did.tf, deployment/terraform/dataspace/gaiax-did.tf, deployment/terraform/dataspace/main.tf, deployment/terraform/participant/did.tf, deployment/terraform/participant/main.tf, system-tests/resources/webdid/company1/did.json, system-tests/resources/webdid/company2/did.json, system-tests/resources/webdid/company3/did.json, system-tests/resources/webdid/registration-service/did.json
This PR adds a reference to the Self-Description endpoint exposed by the Identity Hub in all DID documents (participants + authority).
DID document should reference all service endpoints that can be targeted externally, which includes the Self-Description endpoint.
Closes https://github.com/agera-edc/MinimumViableDataspace/issues/187
=> feat: Add link to self-description in DID document

.github/workflows/deploy.yaml, .github/workflows/destroy.yaml, deployment/terraform/dataspace/main.tf, deployment/terraform/participant/main.tf, docs/developer/continuous-deployment/continuous_deployment.md, resources/setup_azure_ad/gh-actions.tf, resources/setup_azure_ad/outputs.tf, resources/setup_azure_ad/set-gh-secrets.sh
Authenticate Terraform to ARM using [Service Principal with Open ID Connect](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_oidc) instead of [Service Principal with a Client Secret](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret)
This simplifies setup and increases security.
Support for OpenID Connect was added in version 3.7.0 of the Terraform AzureRM provider.
Closes https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace/issues/78
=> chore: Terraform OIDC

system-tests/docker-compose.yml
Fix incorrect context path of Registration Service.
Closes #85
=> fix: Fix context path for Registration Service in docker-compose file

Vision Demonstrator/Vision Demonstrator Introduction.md
Link to the figma export file was broken
User can't download the figma tool from the Vision Demonstrator page.
=> Correct link to figma export file

launchers/connector/build.gradle.kts, launchers/registrationservice/build.gradle.kts
Adds a dependency on the `identity-hub-credentials-jwt` module to both launchers (`connector` and `registrationservice`).
Due to the missing dependency registration of verifiable crendentials at the Identity Hub failed. Thus, the catalog browser was always empty.
=> fix: add missing JWT credentials dependency

system-tests/README.md
Resolves markdown syntax mistakes that where introduced in #112.
As described in #110
--
Relates #109
=> fix(docs): resolve markdown syntax errors

gradle.properties, settings.gradle.kts
Sets the version for all EDC dependencies to `0.0.1-20230301-SNAPSHOT`. Updates names of dependencies that have changed.
So that the main branch of the MVD successfully builds.
This keeps the issue mentioned in #132 from occurring, but the MVD should still be updated to fix that issue. The problem causing this issue seems to be refactoring in the RegistrationService repository:
- the package name of `ParticipantDto` has changed, which is an easy fix
- `RegistryApi` and `ApiClientFactory` have been refactored (not just renamed) so the `RegistrationServiceNodeDirectoryExtension` int the MVD fails to initialize
=> fix: set EDC dependencies to fixed version

.github/workflows/cloud-cd.yaml, README.md, deployment/azure/create_dataspace_resources.sh, deployment/azure/create_participant_resources.sh, deployment/azure/seed_vcs.sh, docs/developer/continuous-deployment/continuous_deployment.md, system-tests/README.md
Fixes the Cloud CD pipeline and the associated Run Azure Dataspace Tests pipeline.
Updates the documentation, removed outdated information.
As reported in the issue #124, the CLOUD CD pipeline stopped working.
The number of pushed credentials was reduced in commit [24c85f2](https://github.com/eclipse-edc/MinimumViableDataspace/commit/24c85f2c7704b86d18b1e0a8e5f5be59d727b514) (PR #119) but `checkCredentials` was not updated accordingly, causing the pipeline to fail.
The `EDC_VAULT_TENANTID` was missing in the `Participant` and `RegistrationService` creation files.
Closes #124 
Closes #95 
@aykhara
=> fix: CLOUD-CD pipeline

.github/workflows/cd.yaml, .github/workflows/initialize.yaml, .github/workflows/run_azure_dataspace_tests.yaml, docs/developer/continuous-deployment/continuous_deployment.md, resources/setup_azure_ad/variables.tf
- Add the `--overwrite` parameter to command `az storage blob upload` as mentioned in this [issue](https://github.com/Azure/azure-cli/issues/21779).
- Remove references to Azure Container Registry
- Upgrade the docker compose version to V2 in `cd.yaml`
- The absence of the `--overwrite` parameter in the `az storage blob upload` command prevents a successful execution of the [run_azure_dataspace_tests.yaml](https://github.com/eclipse-edc/MinimumViableDataspace/actions/runs/4742734427/jobs/8421373780) pipeline when the blob storage already exists.
- Since the `Deploy` pipeline has been removed (#128) there is no need to create an Azure Container Registry.
- Upgrading to docker compose V2 in cd.yaml as suggested by @paullatzelsperger in PR #137.
Closes #128
=> refactor: update pipelines

extensions/policies/src/test/java/org/eclipse/edc/mvd/RegionConstraintFunctionTest.java, gradle.properties, gradle/libs.versions.toml, system-tests/README.md
Update EDC components version to `0.1.2` (latest at 26JUN2023).
=> chore: Bump EDC components version to 0.1.2

deployment/data/MVD.postman_collection.json
Updates the postman collection to comply with the DataPlane Selector API contained in EDC 0.1.4-SNAPSHOT and later.
functional compliance
- this PR should only be merged _after_ the next version bump of EDC.
=> chore: update to latest DPS-api

.github/actions/gradle-setup/action.yml, .github/workflows/run_azure_dataspace_tests.yaml, deployment/azure/docker/docker-compose.yml, resources/setup_azure_ad/main.tf, system-tests/docker-compose.yml, system-tests/resources/appconfig/company1/app.config.json, system-tests/resources/appconfig/company2/app.config.json, system-tests/resources/appconfig/company3/app.config.json
- Configuration and paths were adapted to the dashboard
- Versions of dependencies have been increased 
Current configurations for the data dashbaoard do not work
Docker Compose and Terraform Proivider visions have been increased
=> fix: Adapt MVD to current version of Data Dashboard

README.md
Changes the path of the text-document.txt in the README.
Fixing
Closes #201
=> fix: change text-document.txt path in README

gradle/libs.versions.toml, launchers/connector/build.gradle.kts
adds the `/v1/version` API to the connector runtimes
to demonstrate the Version API
=> feat(api): add version API to connector runtimes

README.md, deployment/postman/http-client.env.json
The change includes the environment file that can be used to launch the postman collection using the HTTP Client plugin for IntelliJ
HTTP Client plugin can import Postman collections and execute them, provided an environment file with the properties:
https://blog.jetbrains.com/idea/2023/09/import-postman-collections-to-the-http-client/
=> feat: environment file for HTTP Client plugin (IntelliJ)

deployment/postman/MVD.postman_collection.json
- when importing with HTTP client plugin in IntelliJ, only one key is generated
=> chore: consistent case for X-Api-Key in postman collection

deployment/assets/env/consumer_connector.env, deployment/assets/env/provider_connector_manufacturing.env, deployment/assets/env/provider_connector_qna.env
- to avoid spaces at the end of env variables key name
=> fix: remove spaces around = in env files

deployment/assets/postgres/edc_schema.sql, gradle/libs.versions.toml, launchers/controlplane/build.gradle.kts
adds Postgres modules for the FC Cache
feature parity with other modules
Closes #282 
=> feat: add FC Cache Postgres modules

.github/workflows/run-e2e-tests.yml, gradle/libs.versions.toml, tests/end2end/build.gradle.kts, tests/end2end/src/test/java/org/eclipse/edc/demo/tests/transfer/TransferEndToEndTest.java
use proper deserialization of the `Catalog[]` response, so we can filter for the `asset-1` of the `provider-qna` connector.
previously it used hard-coded indices in JSONPath expressions, which is brittle due to the non-canonical form of JSON.
=> fix: flaky integration test

.run/Connector Consumer Corp.run.xml, .run/Connector _provider-manufacturing_.run.xml, .run/Connector _provider-qna_.run.xml, .run/IdentityHub Consumer Corp.run.xml, .run/IdentityHub Provider Corp.run.xml, .run/Provider Catalog Server.run.xml, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
updates the Gradle Wrapper, which requires Java 22 in the run configurations
=> chore: update Gradle Wrapper and JDK runtime

README.md, deployment/postman/MVD.postman_collection.json, gradle.properties, gradle/libs.versions.toml, launchers/catalog-server/build.gradle.kts, launchers/dataplane/build.gradle.kts, tests/end2end/src/test/resources/negotiation-request.json
improves JSON-LD objects in Management API by including the `management-api-json-ld-context` extension which includes the experimental JSON-LD context for the management API available [here](https://w3id.org/edc/connector/management/v0.0.1)
Also changed the payloads in the postman collections and the Readme file.
The EDC deps also was bumped to `0.10.0-SNAPSHOT`
improves JSON-LD usability
The `@context` output will still contains namespaces prefix as `edc` or `odrl` and the `@vocab`. 
Once [this](https://github.com/eclipse-edc/Connector/issues/4455) is accepted as feature request and implemented, it will be possible to have a clean `@context` output
_Please be sure to take a look at the [contributing …
=> feat: improves JSON-LD objects

deployment/assets/postgres/ih_schema.sql
This change adds the missing `key_context` in `keypair_resource` that was introduced in https://github.com/eclipse-edc/IdentityHub/pull/451.
Without having this column the services start with an error and does not work as expected:
```
Exception in thread "main" org.eclipse.edc.spi.EdcException: org.eclipse.edc.spi.persistence.EdcPersistenceException: ERROR: column "key_context" of relation "keypair_resource" does not exist
Position: 181
at org.eclipse.edc.boot.system.runtime.BaseRuntime.onError(BaseRuntime.java:143)
at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:106)
at org.eclipse.edc.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:77)
Caused by: org.eclipse.edc.spi.persistence.EdcPersistenceException: ERROR: column "key_context" of relation …
```
=> fix: `ih_schema.sql` to comply with eclipse-edc/IdentityHub#451

deployment/postman/MVD.postman_collection.json
The headers `Authorization` is already defined on the collection-level, so adding them to each request is redundant on the individual requests.
Removing the headers on the individual requests, which should make no difference to the actual requests send out by Postman.
Closes #347.
=> fix: postman headers

gradle/libs.versions.toml, launchers/identity-hub/build.gradle.kts
adds the newly created STS account service (local) module
automatic STS Account provisioning
also adds the SQL STS Account Store module
=> fix: add STS Account provisioner module

.github/workflows/test-controlplane-management.yml
updates the workflow to be in line with other WF names
removes NPM and newman install
=> chore: rename WF, remove newman install

launchers/catalog-server/build.gradle.kts
Since the `management-api` bom includes the `edr-api`, this PR adds also the EDR store as dependency for the catalog server
=> chore: fixes catalog server boot faulire

extensions/dcp-impl/build.gradle.kts, extensions/dcp-impl/src/main/java/org/eclipse/edc/demo/dcp/core/DcpPatchExtension.java, extensions/dcp-impl/src/main/java/org/eclipse/edc/demo/dcp/core/DefaultScopeMappingFunction.java, extensions/dcp-impl/src/main/java/org/eclipse/edc/demo/dcp/policy/DataAccessLevelFunction.java, extensions/dcp-impl/src/main/java/org/eclipse/edc/demo/dcp/policy/MembershipCredentialEvaluationFunction.java, extensions/dcp-impl/src/main/java/org/eclipse/edc/demo/dcp/policy/PolicyEvaluationExtension.java, gradle/libs.versions.toml
fixes compile errors that were introduced by some upstream changes.
now, MVD already uses the new type-based Policy evaluation framework.
fix compile errors, avoid technical debt
Closes #360
=> fix: use new type-based Policy evaluation framework

deployment/modules/identity-hub/main.tf, deployment/provider.tf, gradle/libs.versions.toml, launchers/controlplane/build.gradle.kts
enable JTI Validation.
To achieve that, IdentityHub and STS need to share a database
(implicitly) Closes #367
=> feat: activate JTI Validation

.github/workflows/run-e2e-tests.yml
post the result of the nightly E2E test run to discord
being able to react when something breaks
- should be merged after #366 
=> feat(ci): post to discord on failed builds

.run/Connector Consumer Corp.run.xml, .run/Connector _provider-manufacturing_.run.xml, .run/IdentityHub Consumer Corp.run.xml, .run/Provider Catalog Server.run.xml, build.gradle.kts, gradle.properties
updates the JDK version of the runconfigs to a LTS version, updates to use latest EDC snapshots
=> chore: update run configs and EDC version

extensions/dcp-impl/src/main/java/org/eclipse/edc/demo/dcp/core/DcpPatchExtension.java
adds post validator for RequestVersionPolicyContext, which makes possible to invoke
the v4alpha enpoint for fetching the counter party protocol version
=> chore: adds post validator for RequestVersionPolicyContext

deployment/issuer.tf, deployment/modules/issuer/main.tf, deployment/postman/MVD K8S.postman_environment.json, deployment/postman/MVD Local Development.postman_environment.json, deployment/postman/MVD.postman_collection.json, seed-k8s.sh, tests/end2end/src/test/java/org/eclipse/edc/demo/tests/issuance/CredentialIssuanceEndToEndTest.java
this PR adopts the `DatabaseAttestationSources` that were introduced in https://github.com/eclipse-edc/IdentityHub/pull/649 by seeding the database and adapting the postman collection
feature display
=> feat: seed issuer for database attestations
